USE EdTech;
GO

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
BEGIN TRANSACTION;
    SELECT * FROM Teacher;
COMMIT TRANSACTION;
GO

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;
BEGIN TRANSACTION;
    SELECT * FROM Teacher;

    WAITFOR DELAY '00:00:05';

    SELECT * FROM Teacher;
COMMIT TRANSACTION;
GO

SET TRANSACTION ISOLATION LEVEL REPEATABLE READ;
BEGIN TRANSACTION;
    SELECT * FROM Teacher;

    WAITFOR DELAY '00:00:05';

    SELECT * FROM Teacher;
COMMIT TRANSACTION;
GO

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;
BEGIN TRANSACTION;
    SELECT * FROM Teacher;

    WAITFOR DELAY '00:00:05';

    SELECT * FROM Teacher;
COMMIT TRANSACTION;
GO

